title: Hanlien
logo: /assets/img/profile.jpeg
email: hschoi5542@gmail.com
description: 안드로이드 주니어 개발자의 공부내용을 끄적이는 공간입니다.
show_downloads: false
google_analytics: UA-108144808-1
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
